# Generated by Django 4.1.5 on 2023-01-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllNid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxListed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nid', models.IntegerField()),
                ('has_tin', models.BooleanField()),
                ('allnid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxapp.allnid')),
            ],
        ),
    ]
