# Generated by Django 4.1.5 on 2023-01-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nid', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AllNid',
            new_name='Citizen',
        ),
        migrations.DeleteModel(
            name='TaxListed',
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='allnid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxapp.citizen'),
        ),
    ]
