# Generated by Django 4.1.5 on 2023-01-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0003_remove_taxpayer_allnid_delete_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('nid', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nid', models.IntegerField()),
            ],
        ),
    ]
