# Generated by Django 4.1.5 on 2023-01-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0004_bank_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='acno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='nid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='nid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='nid',
            field=models.IntegerField(null=True),
        ),
    ]
