# Generated by Django 4.1.5 on 2023-01-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0005_bank_acno_alter_bank_balance_alter_bank_bname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='cname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxapp.citizen'),
        ),
    ]
